/**
 * server/rag/study-gen.ts â€” generate a per-course "study set" from the syllabus
 * material: flashcards, a multiple-choice quiz, an auto-summary and a mind map.
 *
 * Same shape as graph-gen.ts / schedule-gen.ts: one gateway (gpt-5.4) JSON call
 * â†’ validated + normalized rows. Powers the "Ãrea de Estudio" window.
 */

import { z } from "zod"
import { flags } from "@/lib/config/flags"

// ---------- public shape (what the UI consumes) ----------

export interface Flashcard {
  front: string
  back: string
}

export interface QuizQuestion {
  question: string
  options: string[] // 2â€“5 options
  answer: number // index into options
  explanation: string
  /** Topic this question assesses (a mind-map branch / weighted topic label). Feeds the mastery ledger. */
  topic?: string
}

export interface SummaryConcept {
  termino: string
  definicion: string
}

export interface Summary {
  titulo: string
  temaPrincipal: string
  introduccion: string
  ideasPrincipales: string[]
  conceptos: SummaryConcept[]
  conclusion: string
}

export interface MindBranch {
  label: string
  items: string[]
}

/**
 * Presentation mode for the mind map — the LLM produces a genuinely different
 * structure per mode (not just a re-layout), so each is generated by its own
 * mindmapAgent call:
 *  - radial: broad overview, one branch per main topic (today's default shape).
 *  - profundidad: deep dive on ONE topic (requires a focus topic) — the topic's
 *    own subtopics, in depth.
 *  - ideas: the material's big ideas only — terse, high-level, few/no sub-items.
 *  - bloques: a vertical block report (headers + stacked cards) — better than a
 *    branch fan for narrative/procedural material or when there's no clean topic
 *    breakdown to fan out.
 */
export type MindMode = "radial" | "profundidad" | "ideas" | "bloques"

export interface MindBlockCard {
  title: string
  body: string
}

export interface MindBlock {
  header: string
  cards: MindBlockCard[]
}

export interface Mindmap {
  mode: MindMode
  center: string
  /** Populated for radial/profundidad/ideas; empty for bloques. */
  branches: MindBranch[]
  /** Populated only when mode === "bloques". */
  blocks?: MindBlock[]
}

/**
 * Pick the best mind-map mode for the content, absent an explicit override
 * (the edit drawer lets the student pick one manually). Pure heuristic, no LLM
 * call — cheap enough to run on every default load:
 *  - a focus topic means the student wants to go deep on THAT topic,
 *  - very few weighted topics means the material doesn't fan out into a clean
 *    branch tree — either it's sparse (few ideas) or it's dense/narrative
 *    (better as a block report),
 *  - otherwise the classic radial overview is the best default.
 */
export function pickMindMode(input: {
  topic?: string
  weightedTopics?: { label: string; weight: number }[]
}): MindMode {
  if (input.topic?.trim()) return "profundidad"
  const n = (input.weightedTopics ?? []).filter((t) => t.label.trim().length > 0).length
  if (n === 0) return "bloques"
  if (n <= 3) return "ideas"
  return "radial"
}

/** A weighted study-guide section, ordered by exam importance. */
export interface StudyGuideSection {
  topic: string
  weight: number // 0â€“100 (exam weight, 0 when unknown)
  points: string[]
}

/**
 * Bump when the generator output shape / prompt contract changes meaningfully.
 * The versioned cache reuses a stored set only when its schema_version matches,
 * so a bump invalidates every cached set after deploy.
 */
export const STUDY_SCHEMA_VERSION = 5

export interface StudySet {
  flashcards: Flashcard[]
  quiz: QuizQuestion[]
  summary: Summary
  mindmap: Mindmap
  /** Ordered, weight-prioritized study guide (Sprint 4). Optional for old cached sets. */
  studyGuide?: StudyGuideSection[]
}

// ---------- LLM contract ----------

const StudySchema = z.object({
  flashcards: z.array(z.object({ front: z.string(), back: z.string() })),
  quiz: z.array(
    z.object({
      question: z.string(),
      options: z.array(z.string()),
      answer: z.number(),
      explanation: z.string(),
      // Optional so old cached sets (no topic) still validate.
      topic: z.string().optional(),
    }),
  ),
  summary: z.object({
    titulo: z.string(),
    temaPrincipal: z.string(),
    introduccion: z.string(),
    ideasPrincipales: z.array(z.string()),
    conceptos: z.array(z.object({ termino: z.string(), definicion: z.string() })),
    conclusion: z.string(),
  }),
  mindmap: z.object({
    center: z.string(),
    branches: z.array(z.object({ label: z.string(), items: z.array(z.string()) })),
  }),
  studyGuide: z
    .array(z.object({ topic: z.string(), weight: z.number(), points: z.array(z.string()) }))
    .optional(),
})

type RawStudy = z.infer<typeof StudySchema>

/**
 * Shared content policy for EVERY study-generation agent (flashcard, inquisitor,
 * synth) and the Critic that gates them. THE key rule: teach the course's SUBJECT,
 * not the syllabus document.
 *
 * The uploaded material is frequently just an outline (topic titles, schedule, exam
 * weights). The only things "literally in it" are then administrative, so anchoring
 * strictly to the verbatim text yields useless meta-questions ("in which week is X
 * taught?", "what % is the midterm worth?"). Instead, develop the established
 * academic content of the topics the course names, so the student is taught and
 * tested on the actual subject. Keep generator and critic wording in sync via this
 * one constant â€” if they diverge, the gate quietly undoes the generator.
 */
export const SUBJECT_GROUNDING_POLICY =
  "GROUND IN THE SUBJECT, NOT THE DOCUMENT. The material may be full course notes OR just a " +
  "syllabus/outline (topic titles, schedule, weights). Build every item from the ACADEMIC CONTENT of " +
  "the course's topics: when the material explains a concept, use that explanation; when it only NAMES " +
  "a topic, develop that topic's standard, well-established subject content yourself (definitions, " +
  "principles, methods, worked reasoning, examples) so the student learns and is tested on the actual " +
  "subject. NEVER write items about the document's administrative or structural metadata â€” schedule, " +
  "dates, weeks/session numbers, exam or assignment weights/percentages, grading policy, instructor, " +
  "bibliography entries, or 'what the syllabus/program says'. Stay strictly ON the course's topics: do " +
  "not drift to unrelated subjects, and do not fabricate course-specific particulars (made-up figures, " +
  "fake citations, invented data presented as if from the material). Write everything in the OUTPUT " +
  "LANGUAGE directive when one is given; otherwise preserve the language of the material."

/**
 * Validate + normalize a raw model object into a safe StudySet.
 * Pure (no network) so it can be unit-tested:
 *  - drops empty flashcards / quiz questions,
 *  - keeps quiz items with â‰¥2 options and clamps `answer` into range,
 *  - trims strings.
 * Returns null when the material yielded nothing usable.
 */
export function normalizeStudySet(raw: unknown): StudySet | null {
  const parsed = StudySchema.safeParse(raw)
  if (!parsed.success) return null
  const r: RawStudy = parsed.data

  const flashcards: Flashcard[] = r.flashcards
    .map((f) => ({ front: f.front.trim(), back: f.back.trim() }))
    .filter((f) => f.front.length > 0 && f.back.length > 0)

  const quiz: QuizQuestion[] = r.quiz
    .map((q) => {
      const options = q.options.map((o) => o.trim()).filter((o) => o.length > 0)
      const answer = Math.min(Math.max(Math.trunc(q.answer), 0), Math.max(options.length - 1, 0))
      const topic = q.topic?.trim()
      return {
        question: q.question.trim(),
        options,
        answer,
        explanation: q.explanation.trim(),
        ...(topic ? { topic } : {}),
      }
    })
    .filter((q) => q.question.length > 0 && q.options.length >= 2)

  const summary: Summary = {
    titulo: r.summary.titulo.trim(),
    temaPrincipal: r.summary.temaPrincipal.trim(),
    introduccion: r.summary.introduccion.trim(),
    ideasPrincipales: r.summary.ideasPrincipales.map((i) => i.trim()).filter(Boolean),
    conceptos: r.summary.conceptos
      .map((c) => ({ termino: c.termino.trim(), definicion: c.definicion.trim() }))
      .filter((c) => c.termino.length > 0 && c.definicion.length > 0),
    conclusion: r.summary.conclusion.trim(),
  }

  const branches: MindBranch[] = r.mindmap.branches
    .map((b) => ({ label: b.label.trim(), items: b.items.map((i) => i.trim()).filter(Boolean) }))
    .filter((b) => b.label.length > 0)

  const studyGuide: StudyGuideSection[] = (r.studyGuide ?? [])
    .map((s) => ({
      topic: s.topic.trim(),
      weight: Math.min(Math.max(s.weight, 0), 100),
      points: s.points.map((p) => p.trim()).filter(Boolean),
    }))
    .filter((s) => s.topic.length > 0 && s.points.length > 0)
    .sort((a, b) => b.weight - a.weight)

  const set: StudySet = {
    flashcards,
    quiz,
    summary,
    mindmap: { mode: "radial", center: r.mindmap.center.trim(), branches },
    ...(studyGuide.length > 0 ? { studyGuide } : {}),
  }

  // Nothing usable at all â†’ signal "not enough material".
  if (
    set.flashcards.length === 0 &&
    set.quiz.length === 0 &&
    set.summary.ideasPrincipales.length === 0
  ) {
    return null
  }
  return set
}

/**
 * Shuffle a question's options (Fisher-Yates) remapping `answer` to follow the
 * correct option. Applied at SERVE time (not generation) so items already
 * persisted with a position-biased `answer` are covered too, and the same item
 * shows a different order on every serve. `rand` is injectable for deterministic
 * tests (defaults to Math.random). Pure â€” returns a new object.
 */
export function shuffleQuizOptions(
  q: QuizQuestion,
  rand: () => number = Math.random,
): QuizQuestion {
  const order = q.options.map((_, i) => i)
  for (let i = order.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[order[i], order[j]] = [order[j], order[i]]
  }
  return {
    ...q,
    options: order.map((i) => q.options[i]),
    answer: order.indexOf(q.answer),
  }
}

export type Difficulty = "facil" | "medio" | "dificil"

/** Preferred flashcard style (Configuración → Formato de tarjetas). */
export type CardFormat = "qa" | "cloze" | "definition" | "mixed"

export interface StudyGenOptions {
  /** Tunes how demanding the generated quiz/flashcards are. Default "medio". */
  difficulty?: Difficulty
  /**
   * Output language for all generated study material (BCP-47-ish code, e.g.
   * "es"). Defaults to the app-wide `flags.studyLanguage`. There is no per-user
   * language system yet — when one lands, pass the user's preference here.
   */
  language?: string
  /** When set, focus the material on this specific topic (from the cronograma). */
  topic?: string
  /** Mind-map presentation mode. Defaults to `pickMindMode`'s heuristic when omitted. */
  mindMode?: MindMode
  /** Course graph topics + exam weights â€” bias generation & order the study guide by importance. */
  weightedTopics?: { label: string; weight: number }[]
  /**
   * Flashcard fronts / quiz questions ALREADY in the item bank. The model is told
   * not to repeat them, so every refresh yields genuinely new items (anti-repeat).
   */
  excludeSeen?: string[]
  /**
   * Preferred flashcard style (user preference). Only the flashcard agent
   * consumes it; omitted → the agent's default mix.
   */
  cardFormat?: CardFormat
}

const DIFFICULTY_HINT: Record<Difficulty, string> = {
  facil:
    "DIFFICULTY: EASY. Stick to foundational concepts and definitions, straightforward recall, simple wording. Quiz distractors should be clearly wrong.",
  medio:
    "DIFFICULTY: MEDIUM. Balance recall with light application. Quiz distractors should be plausible but distinguishable.",
  dificil:
    "DIFFICULTY: HARD. Emphasize reasoning, edge cases, application and analysis over recall. Quiz distractors must be subtle and tempting; explanations must justify why each is wrong.",
}

/** Build the extra instruction block from language + difficulty + optional topic focus. Pure â†’ testable. */
export function buildDirectives(opts: StudyGenOptions): string {
  const lang = (opts.language ?? flags.studyLanguage).trim() || flags.studyLanguage
  const lines = [
    `OUTPUT LANGUAGE: "${lang}". Write ALL generated content (flashcards, quiz questions, options, ` +
      `explanations, summary, mind-map labels, study guide) in this language, regardless of the ` +
      `material's language. Keep proper nouns and established technical terms as commonly used.`,
    DIFFICULTY_HINT[opts.difficulty ?? "medio"],
  ]
  const topic = opts.topic?.trim()
  if (topic) {
    lines.push(
      `FOCUS: Follow this user instruction when generating the material: "${topic}". Treat it as the scope/emphasis â€” prioritize content from the material that matches it and ignore unrelated sections. If the material barely covers it, do your best with what is present (still never invent facts). ` +
        `For the SUMMARY specifically: "titulo" and "temaPrincipal" must be this focus topic itself (not the whole course), and "ideasPrincipales"/"conceptos"/"conclusion" must center on it. Only bring in another closely related topic if it's genuinely needed to understand this one â€” that's optional, don't force it.`,
    )
  }
  const weighted = (opts.weightedTopics ?? [])
    .filter((t) => t.label.trim().length > 0)
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 12)
  if (weighted.length > 0) {
    const list = weighted.map((t) => `- ${t.label} (${Math.round(t.weight)}%)`).join("\n")
    lines.push(
      "WEIGHTED TOPICS (exam importance, highest first). Prioritize the heavier topics: allocate more flashcards/quiz questions to them, set each quiz question's `topic` to the matching label, and order `studyGuide` from heaviest to lightest weight:\n" +
        list,
    )
  }
  const seen = (opts.excludeSeen ?? [])
    .map((s) => s.trim())
    .filter(Boolean)
    .slice(0, 120)
  if (seen.length > 0) {
    const list = seen.map((s) => `- ${s}`).join("\n")
    lines.push(
      "ALREADY COVERED â€” do NOT repeat or lightly reword any of these; generate flashcards and quiz " +
        "questions about DIFFERENT concepts, angles or applications from the material:\n" +
        list,
    )
  }
  return lines.join("\n")
}
