/**
 * llm/tools-loop.ts — Provider-agnostic tool-calling loop.
 *
 * Runs a NON-streamed completion with `tools` enabled, executes any tool calls
 * the model requests via an injected executor, feeds the results back, and
 * loops until the model stops calling tools (or the round cap is hit).
 *
 * Layering: this module stays a pure LLM capability. It does NOT import the
 * Actions & Tools layer (`lib/tools`) — the caller (chat.service) passes the
 * tool definitions + an `execute` bridge. That keeps llm ⟂ tools ⟂ services.
 *
 * Output is a plain-text transcript of what the tools returned, meant to be
 * injected as extra context into the subsequent STREAMED answer. We don't
 * stream from inside the loop, so the live SSE path in chat.service is untouched.
 */

import type { LLMConfig, LLMMessage } from "./types"
import type { OpenAIToolDef } from "@/lib/tools/types"
import { getOpenAIClient, buildOpenAIParams } from "./providers/openai"
import { getOpenRouterClient } from "./providers/openrouter"
import { logError, logInfo, logWarn } from "@/lib/observability/logger"
import type OpenAI from "openai"

/** Result of one tool execution, surfaced for the transcript + observability. */
export interface ToolCallRecord {
  name: string
  args: Record<string, unknown>
  ok: boolean
  error?: string
}

export interface ToolLoopResult {
  /** Plain-text block summarizing tool results to inject before streaming. */
  transcript: string
  /** Tool calls executed across all rounds. */
  calls: ToolCallRecord[]
  /** Rounds the model used (0 = no tools called). */
  rounds: number
  usage: { promptTokens: number; completionTokens: number; totalTokens: number }
}

/** Execute-a-tool bridge the caller provides (binds request context). */
export type ToolExecutor = (
  name: string,
  args: Record<string, unknown>,
) => Promise<{ ok: boolean; data?: unknown; error?: string }>

const EMPTY: ToolLoopResult = {
  transcript: "",
  calls: [],
  rounds: 0,
  usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
}

function pickClient(config: LLMConfig): OpenAI | null {
  try {
    return config.provider === "openrouter" ? getOpenRouterClient() : getOpenAIClient()
  } catch {
    return null
  }
}

/** Safely JSON-parse tool-call arguments; never throws. */
function parseArgs(raw: string | undefined): Record<string, unknown> {
  if (!raw) return {}
  try {
    const parsed = JSON.parse(raw)
    return parsed && typeof parsed === "object" ? (parsed as Record<string, unknown>) : {}
  } catch {
    return {}
  }
}

/**
 * Run the tool-calling loop.
 *
 * @param messages  Conversation so far (system + history + user turn).
 * @param config    Provider/model to use for the resolution pass.
 * @param tools     OpenAI-format tool definitions (from lib/tools).
 * @param execute   Bridge that actually runs a tool by name.
 * @param maxRounds Safety cap on tool-call rounds (default 4).
 */
export async function runToolLoop(
  messages: LLMMessage[],
  config: LLMConfig,
  tools: OpenAIToolDef[],
  execute: ToolExecutor,
  maxRounds = 4,
): Promise<ToolLoopResult> {
  if (tools.length === 0) return EMPTY
  const client = pickClient(config)
  if (!client) {
    logWarn("llm.tools_loop.no_client", { provider: config.provider })
    return EMPTY
  }

  // Work in native OpenAI message format so tool_call_id pairing is valid.
  const convo: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = messages.map((m) => ({
    role: m.role,
    content: m.content,
  }))

  const calls: ToolCallRecord[] = []
  let promptTokens = 0
  let completionTokens = 0
  let totalTokens = 0
  let rounds = 0

  try {
    for (let round = 0; round < maxRounds; round++) {
      const completion = await client.chat.completions.create({
        model: config.model,
        messages: convo,
        // OpenAI's FunctionParameters carries an index signature our fixed-shape
        // ToolParameterSchema doesn't; the runtime shape is identical.
        tools: tools as unknown as OpenAI.Chat.Completions.ChatCompletionTool[],
        tool_choice: "auto",
        ...buildOpenAIParams(config.model, config),
      })

      const usage = completion.usage
      promptTokens += usage?.prompt_tokens ?? 0
      completionTokens += usage?.completion_tokens ?? 0
      totalTokens += usage?.total_tokens ?? 0

      const choice = completion.choices[0]?.message
      const toolCalls = choice?.tool_calls ?? []

      // No tool calls → model is done deciding; stop. We discard its draft text
      // because the final answer is generated by the streamed call downstream.
      if (toolCalls.length === 0) break
      rounds = round + 1

      // Record the assistant turn carrying the tool calls (required for pairing).
      convo.push({
        role: "assistant",
        content: choice?.content ?? "",
        tool_calls: toolCalls,
      })

      // Execute each requested tool, append its result keyed by tool_call_id.
      for (const tc of toolCalls) {
        if (tc.type !== "function") continue
        const name = tc.function.name
        const args = parseArgs(tc.function.arguments)
        const result = await execute(name, args)
        calls.push({ name, args, ok: result.ok, error: result.error })
        convo.push({
          role: "tool",
          tool_call_id: tc.id,
          content: JSON.stringify(result.ok ? (result.data ?? {}) : { error: result.error }),
        })
      }
    }
  } catch (err) {
    logError("llm.tools_loop.error", {
      provider: config.provider,
      model: config.model,
      error: err instanceof Error ? err.message : String(err),
    })
    // Return whatever was gathered so far rather than failing the whole turn.
  }

  const okCalls = calls.filter((c) => c.ok)
  logInfo("llm.tools_loop.done", {
    rounds,
    calls: calls.length,
    okCalls: okCalls.length,
    totalTokens,
  })

  return {
    transcript: buildTranscript(calls, convo),
    calls,
    rounds,
    usage: { promptTokens, completionTokens, totalTokens },
  }
}

/**
 * Render the executed tool results into a plain-text block for injection into
 * the streamed answer. Pulls each tool's JSON result back out of the native
 * conversation (the `tool` messages) so the downstream model sees the data.
 */
function buildTranscript(
  calls: ToolCallRecord[],
  convo: OpenAI.Chat.Completions.ChatCompletionMessageParam[],
): string {
  if (calls.length === 0) return ""
  const toolMsgs = convo.filter(
    (m): m is OpenAI.Chat.Completions.ChatCompletionToolMessageParam => m.role === "tool",
  )
  const lines: string[] = []
  let i = 0
  for (const c of calls) {
    const content = typeof toolMsgs[i]?.content === "string" ? (toolMsgs[i].content as string) : ""
    i++
    if (c.ok) {
      lines.push(`- ${c.name} → ${content}`)
    } else {
      lines.push(`- ${c.name} → (error: ${c.error ?? "desconocido"})`)
    }
  }
  return (
    `Resultados de herramientas (úsalos para responder; no inventes más allá de esto):\n` +
    lines.join("\n")
  )
}
