import { GraphRepository } from "../repositories/graph.repo"
import type { LayoutKind } from "../repositories/graph.repo"
import { DocumentRepository } from "../repositories/document.repo"
import { JobRepository } from "../repositories/job.repo"
import { ApiErrorResponse } from "../utils/auth-helpers"
import { validateNoCycles, validateTree } from "../rag/graph-gen"
import type { GraphUpdateInput } from "../validators/api.schemas"
import type { GraphResponseAPI } from "@/types/api"
import { StudyInvalidationService } from "./study-invalidation.service"
import { ArtifactRunRepository } from "../repositories/artifact-run.repo"
import { KnowledgePipelineService } from "./knowledge-pipeline.service"

export const GraphService = {
  /**
   * Read the knowledge graph for a syllabus the user owns, shaped for the UI.
   * topics → nodes (tree: level + parent_id + detail + color), topic_dependencies
   * (prerequisite → target) → edges, topic_cross_links → crossLinks.
   * graph_status / graph_error / layout come from the syllabus_uploads row.
   */
  async getGraph(userId: string, syllabusId: string): Promise<GraphResponseAPI> {
    const doc = await DocumentRepository.findByIdAndUser(syllabusId, userId)
    if (!doc) {
      throw new ApiErrorResponse("Syllabus not found", 404)
    }

    const [{ topics, edges, crossLinks }, graphRun, inventoryRun] = await Promise.all([
      GraphRepository.getGraph(syllabusId),
      ArtifactRunRepository.latestForScope(userId, "doc", syllabusId, "document_graph").catch(
        () => undefined,
      ),
      ArtifactRunRepository.latestForScope(userId, "doc", syllabusId, "document_inventory").catch(
        () => undefined,
      ),
    ])
    const latestRun = [graphRun, inventoryRun]
      .filter((run) => run !== undefined)
      .sort((a, b) => Date.parse(b!.created_at) - Date.parse(a!.created_at))[0]
    const runActive = latestRun?.status === "queued" || latestRun?.status === "running"
    const interrupted =
      (doc.graph_status === "pending" || doc.graph_status === "processing") && !runActive
    const visibleStatus = interrupted ? "failed" : doc.graph_status
    const visibleError = interrupted
      ? (latestRun?.error ??
        doc.graph_error ??
        "La generación anterior se interrumpió. Reintenta para crear el mapa.")
      : (doc.graph_error ?? null)

    return {
      syllabus_id: syllabusId,
      graph_status: visibleStatus as GraphResponseAPI["graph_status"],
      graph_error: visibleError,
      layout: (doc.layout as GraphResponseAPI["layout"]) ?? null,
      nodes: topics.map((t) => ({
        id: t.id,
        label: t.label,
        weight_percent: t.weight_percent ?? 0,
        level: t.level,
        parent_id: t.parent_topic_id,
        detail: t.detail,
        color: t.color,
        source_refs: t.source_refs ?? [],
        confidence: t.source_refs?.length ? 0.85 : 0,
        generation_version: 2,
      })),
      edges: edges.map((e) => ({
        source: e.prerequisite_topic_id,
        target: e.target_topic_id,
      })),
      crossLinks: crossLinks.map((c) => ({
        source: c.source_topic_id,
        target: c.target_topic_id,
        label: c.label,
      })),
    }
  },

  /**
   * Replace the whole graph with a user-edited version (manual mind-map edits).
   * Node ids are client-provided (existing topic UUIDs or temp ids for new
   * nodes); they become `external_id` and the repo assigns fresh UUIDs, so the
   * caller should refetch. Rejects invalid trees and prerequisite cycles.
   * `layout` is preserved from the current graph (an edit never changes it);
   * a legacy graph (layout still null — never generated by the new pipeline)
   * defaults to "radial" the first time it's edited, since the legacy editor
   * only ever produces a flat, root-only shape.
   */
  async updateGraph(
    userId: string,
    syllabusId: string,
    input: GraphUpdateInput,
  ): Promise<GraphResponseAPI> {
    const doc = await DocumentRepository.findByIdAndUser(syllabusId, userId)
    if (!doc) throw new ApiErrorResponse("Syllabus not found", 404)

    const ids = new Set(input.nodes.map((n) => n.id))
    // Drop edges/cross-links that reference missing nodes (e.g. after a node deletion).
    const edges = input.edges.filter(
      (e) => ids.has(e.source) && ids.has(e.target) && e.source !== e.target,
    )
    const crossLinks = input.crossLinks.filter(
      (c) => ids.has(c.source) && ids.has(c.target) && c.source !== c.target,
    )

    const nodes = input.nodes.map((n) => ({
      externalId: n.id,
      label: n.label,
      level: n.level,
      parentExternalId: n.parentId && ids.has(n.parentId) ? n.parentId : null,
      weight: n.weight_percent ?? null,
      detail: n.detail ?? null,
    }))

    try {
      validateTree(
        nodes.map((n) => ({ id: n.externalId, level: n.level, parentId: n.parentExternalId })),
      )
    } catch {
      throw new ApiErrorResponse(
        "La jerarquía del mapa es inválida (nivel o rama padre inconsistente).",
        400,
      )
    }

    const prerequisites = edges.map((e) => ({ from: e.source, to: e.target }))
    try {
      validateNoCycles([...ids], prerequisites)
    } catch {
      throw new ApiErrorResponse(
        "El grafo tiene un ciclo de prerrequisitos. Quita la dependencia circular.",
        400,
      )
    }

    await GraphRepository.replaceGraph(syllabusId, {
      topics: nodes,
      prerequisites,
      crossLinks,
      layout: ((doc.layout as LayoutKind | null) ?? "radial") as LayoutKind,
    })
    await DocumentRepository.setGraphStatus(syllabusId, "ready", null)
    await StudyInvalidationService.invalidateDocumentGraph(userId, syllabusId)
    return this.getGraph(userId, syllabusId)
  },

  /**
   * Re-run graph generation through the durable document workflow. The chunk
   * text is already in Neon, so the worker normally skips embedding and rebuilds
   * the academic inventory + graph off-request. Explicit retries may revive an
   * abandoned legacy job, but never duplicate a fresh active worker.
   */
  async reprocess(userId: string, syllabusId: string) {
    const doc = await DocumentRepository.findByIdAndUser(syllabusId, userId)
    if (!doc) {
      throw new ApiErrorResponse("Syllabus not found", 404)
    }

    await DocumentRepository.setGraphStatus(syllabusId, "pending", null)
    await StudyInvalidationService.invalidateDocumentGraph(userId, syllabusId)
    await JobRepository.enqueue("ingest", { syllabusId }, { kickIfPending: true })
    return KnowledgePipelineService.enqueueDocumentGraph(userId, syllabusId)
  },
}
